### ISSUE TITLE
Improve StepperData

### ISSUE THREAD

**Issue by A7MeDG0L0L** [RajnishOnly/another_stepper#11]
Can you make title in StepperData customisable to achive this view
![image](https://user-images.githubusercontent.com/33913003/207552055-f2b068e6-f390-446e-8609-39ad479a59a3.png)

**Comment by RajnishOnly** [comment]
Yes @A7MeDG0L0L I suppose we can make this possible by just changing the stepperData variables. In place of title as `String` and `TextStyle` we can have `Widget`. 

You can fork it and make changes that suits you and you can even make a pull request with the said changes. That would be very helpful.
