### ISSUE TITLE
The named parameter 'dotWidget' isn't defined.

### ISSUE THREAD

**Issue by sampaiopedrodev** [RajnishOnly/another_stepper#14]
Hi,

the property dotWidget has been deleted? it's give me error

**Comment by RajnishOnly** [comment]
Hey @sampaiopedrodev, Yes we have added an enhancement few days back. `dotWidget` was a constant widget for all the steps in the stepper, in order to get different dots/widgets for different steps we moved it to `StepperData`.

Now you can use `iconWidget` is the parameter where you can sent widgets for different steps like this: 
```List<StepperData> stepperData = [
  StepperData(
      title: StepperText(
        "Order Placed",
        textStyle: const TextStyle(
          color: Colors.grey,
        ),
      ),
      subtitle: StepperText("Your order has been placed"),
      iconWidget: Container(
        padding: const EdgeInsets.all(8),
        decoration: const BoxDecoration(
            color: Colors.green,
            borderRadius: BorderRadius.all(Radius.circular(30))),
        child: const Icon(Icons.looks_one, color: Colors.white),
      )),
  StepperData(
      title: StepperText("Preparing"),
      subtitle: StepperText("Your order is being prepared"),
      iconWidget: Container(
        padding: const EdgeInsets.all(8),
        decoration: const BoxDecoration(
            color: Colors.green,
            borderRadius: BorderRadius.all(Radius.circular(30))),
        child: const Icon(Icons.looks_two, color: Colors.white),
      )),
  StepperData(
      title: StepperText("On the way"),
      subtitle: StepperText(
          "Our delivery executive is on the way to deliver your item"),
      iconWidget: Container(
        padding: const EdgeInsets.all(8),
        decoration: const BoxDecoration(
            color: Colors.green,
            borderRadius: BorderRadius.all(Radius.circular(30))),
        child: const Icon(Icons.looks_3, color: Colors.white),
      )),
  StepperData(
    title: StepperText("Delivered",
        textStyle: const TextStyle(
          color: Colors.grey,
        )),
  ),
];

**Comment by sampaiopedrodev** [comment]
@RajnishOnly  I have same thing like:

`List<StepperData> stepperData = [
    StepperData(
        title: StepperText("Especialidade",
            textStyle: TextStyle(
              // color: HexColor('#2C3F48'),
              fontSize: 11,
              fontWeight: FontWeight.bold,
            )),
        iconWidget: Container(
          padding: EdgeInsets.all(8),
          decoration: BoxDecoration(
              color: HexColor('#2C3F48'),
              borderRadius: BorderRadius.circular(30)),
        )),
    StepperData(
        title: StepperText("Local",
            textStyle: TextStyle(
              color: HexColor('#34424B'),
              fontSize: 11,
              fontWeight: FontWeight.bold,
            )),
        iconWidget: Container(
          padding: EdgeInsets.all(8),
          decoration: BoxDecoration(
              color: HexColor('#2C3F48'),
              borderRadius: BorderRadius.circular(30)),
        )),
    StepperData(
        title: StepperText("Data/Hora",
            textStyle: TextStyle(
              color: HexColor('#34424B'),
              fontSize: 11,
              fontWeight: FontWeight.bold,
            )),
        iconWidget: Container(
          padding: EdgeInsets.all(8),
          decoration: BoxDecoration(
              color: HexColor('#2C3F48'),
              borderRadius: BorderRadius.circular(30)),
        )),
    StepperData(
        title: StepperText("Confirmação",
            textStyle: TextStyle(
              color: HexColor('#34424B'),
              fontSize: 11,
              fontWeight: FontWeight.bold,
            )),
        iconWidget: Container(
          padding: EdgeInsets.all(8),
          decoration: BoxDecoration(
              color: HexColor('#2C3F48'),
              borderRadius: BorderRadius.circular(30)),
        )),
  ];
`

**And**

AnotherStepper(
    stepperList: stepperData,
    stepperDirection: Axis.horizontal,
    inverted: true,
    activeBarColor: HexColor('#34424B'),
    inActiveBarColor: HexColor('#2C3F48'),
    activeIndex: 1,
),


**How can i change the iconWidget color (container) when activeIndex change?**

**Comment by RajnishOnly** [comment]
Hey @sampaiopedrodev when you give custom `iconWidget` you can't rely on active index property for the `dotWidget` to change its color. you will have to change it by yourself as `activeIndex` will not have idea about your `iconWidget`. In this scenario, only the stepper line color will be controlled by `activeIndex` property.

**Comment by krishnaacharya-official** [comment]
> @RajnishOnly I have same thing like:
> 
> List stepperData = [ StepperData( title: StepperText("Especialidade", textStyle: TextStyle( // color: HexColor('#2C3F48'), fontSize: 11, fontWeight: FontWeight.bold, )), iconWidget: Container( padding: EdgeInsets.all(8), decoration: BoxDecoration( color: HexColor('#2C3F48'), borderRadius: BorderRadius.circular(30)), )), StepperData( title: StepperText("Local", textStyle: TextStyle( color: HexColor('#34424B'), fontSize: 11, fontWeight: FontWeight.bold, )), iconWidget: Container( padding: EdgeInsets.all(8), decoration: BoxDecoration( color: HexColor('#2C3F48'), borderRadius: BorderRadius.circular(30)), )), StepperData( title: StepperText("Data/Hora", textStyle: TextStyle( color: HexColor('#34424B'), fontSize: 11, fontWeight: FontWeight.bold, )), iconWidget: Container( padding: EdgeInsets.all(8), decoration: BoxDecoration( color: HexColor('#2C3F48'), borderRadius: BorderRadius.circular(30)), )), StepperData( title: StepperText("Confirmação", textStyle: TextStyle( color: HexColor('#34424B'), fontSize: 11, fontWeight: FontWeight.bold, )), iconWidget: Container( padding: EdgeInsets.all(8), decoration: BoxDecoration( color: HexColor('#2C3F48'), borderRadius: BorderRadius.circular(30)), )), ];
> 
> **And**
> 
> AnotherStepper( stepperList: stepperData, stepperDirection: Axis.horizontal, inverted: true, activeBarColor: HexColor('#34424B'), inActiveBarColor: HexColor('#2C3F48'), activeIndex: 1, ),
> 
> **How can i change the iconWidget color (container) when activeIndex change?**

I am also facing the same problem , how to change the color of the icon widget based on the activeIndex ?

**Comment by rajnishsharma1** [comment]
@krishnaacharya-official  you cannot change the color of dot Widget using `activeIndex` when you are using `iconWidget`. 

You can change it from your `iconWidget` directly, I chose this approach as package users might have some data coming from API, which would tell them the color and related decorations of dot widgets.

Note: When you use `iconWidget` only the color of `stepperBar` or the `gap` between the setpper dots would change

**Comment by rajnishsharma1** [comment]
Hey @sampaiopedrodev `iconWidget` would not support color  or decoration change from `activeIndex`, `activeBarColor` and `inactiveBarcolor` because there is no way  to know what widget, user has used there. It can be anything like Button, Text or even some complex custom widget made by  user. 
That is why user has to handle it from their side (for now).

If you have a solution for this, feel free to share.
