### ISSUE TITLE
change color, size and more in title and subtitle please ???

### ISSUE THREAD

**Issue by jtavio** [RajnishOnly/another_stepper#8]
StepperData(
        title: "Information",
        iconWidget: Container(
          padding: const EdgeInsets.all(8),
          child: const Image(
            image: AssetImage('assets/images/one.png'),
            fit: BoxFit.fill,
          ),
        )),

**Comment by RajnishOnly** [comment]
Hey, @jtavio I saw your issue, and thanks a lot to bring it to my attention, I have solved it and created another release.
Now you can change `TextStyle` which includes changing color, size weight and any other thing that you can do with `TextStyle`.

You simply have to send title and subtitle in `StepperText` which contains 2 params: `text` and named param `textStyle` which is optional.

**Comment by jtavio** [comment]
Thanks for seeing the message, if I realized later that I had it, and I put it the way I had it before, but thank you very much for the update, I would like to know if there is a possibility to add an inputFormatters because sometimes it is not very accurate the format that is given by area code I'm trying with CO code (COLOMBIA) and the format changes, I do not know if you want there will be an issues for this. 

![1668455626901](https://user-images.githubusercontent.com/26285721/201753329-77ce2b76-a8fa-4999-87ad-b6abf902079a.jpg)

**Comment by RajnishOnly** [comment]
Anytime @jtavio in the next release I will try to get rid to text `title` and `subtitle` completely, and will put widgets in place of them to make it more generic and usable by more people. Those with different requirements, who wants title and subtitle to be other widgets, they will be able to us it too. Tell me how you like my idea?

And for your question, I didn't completely get it, can you show my the bigger pitcher of what you are trying to achieve here. Then I might be able to help.
